site_name: The PROVES Kit Documentation

theme: 
  name: material
  features:
    - navigation.tabs

plugins:
  - search  # To have search functionality on the document


nav: # Setting up the navigation. The below list will be tabs on left panel
  - Home: index.md
  - Overview: overview.md # Overview of the project
  - Design: design_philosophy.md  # 
  - Assembly Guide: assembly_guide.md # Assembly guide
  - Core Documentation: 
    - Hardware: hardware.md
    - Software: software.md
