site_name: The PROVES Kit Documentation

theme: 
  name: material
  features:
    - navigation.tabs
    - header.autohide
    - navigation.path
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search  # To have search functionality on the document
  - mkdocs-pdf #PDF Embed Ability

markdown_extensions:
  - attr_list
  - md_in_html
  - attr_list
  - abbr
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.pathconverter:
      base_path: 'DOCUMENTATION' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'

nav: # Setting up the navigation. The below list will be tabs on left panel
  - Home: 
    - Welcome: index.md
    - Overview: overview/overview.md
    - Quick Start Guide: quick_start/index.md
    - Assembly Guide: assembly_guide/index.md
    - Core Documentation: core_documentation/index.md
    - Publications: publications.md
  - Overview:  # Overview of the project
    - Overview: overview/overview.md
    - Design Philosophy: overview/design_philosophy.md
    - Kit Elements: overview/kit_elements.md
  - Quick Start Guide: # Quick start guide 
    - Introduction: quick_start/index.md
    - CubeSat Fundamentals: quick_start/cubesat_fundamentals.md
    - Getting Started with PROVES: quick_start/proves_quick_start.md
    - Contact an Orbiting Satellite: quick_start/contacting_proves.md
    - Becoming a Contributor: quick_start/becoming_contributor.md
  - Assembly Guide:
    - Introduction: assembly_guide/introduction.md
    - "Chapter 0: Parts and Tools": assembly_guide/ch_0_parts_tools.md
    - "Chapter 1: Battery Board Preintegration": assembly_guide/ch_1_eps.md
    - "Chapter 2: Feet and Heater Assembly Preintegration": assembly_guide/ch_2_feet.md
    - "Chapter 3: Solar Boards Preintegration": assembly_guide/ch_3_solar.md
    - "Chapter 4: Flight Controller Board Preintegration": assembly_guide/ch_4_fc.md
    - "Chapter 5: Antenna Preintegration": assembly_guide/ch_5_antenna.md
    - "Chapter 6: Structure Preintegration": assembly_guide/ch_6_structure.md
    - "Chapter 7: Preintegration Testing Overview":
      - "Preintegration Testing Index": assembly_guide/ch_7_testing/index.md
      - "Solar Board Testing": assembly_guide/ch_7_testing/solar_board_testing.md
      - "Battery Board Testing": assembly_guide/ch_7_testing/battery_board_testing.md
      - "Flight Controller Testing": assembly_guide/ch_7_testing/flight_computer_testing.md
      - "FlatSat Testing": assembly_guide/ch_7_testing/flatsat_testing.md
    - "Chapter 8: Integration Procedure": assembly_guide/ch_8_integration.md
    - "Chapter 9: Final Tests": assembly_guide/ch_9_final_tests.md
    - assembly_guide/index.md
  - Assembly Guide v1.5:
    - "Chapter 0: Parts and Tools": Assembly_Guide_V2/Chapter_0.md
    - "Chapter 1: Battery Board Preintegration": Assembly_Guide_V2/Chapter_1.md
    - "Chapter 2: Feet and Heater Assembly Preintegration": Assembly_Guide_V2/Chapter_2.md
    - "Chapter 3: Solar Boards Preintegration": Assembly_Guide_V2/Chapter_3.md
    - "Chapter 4: Flight Controller Board Preintegration": Assembly_Guide_V2/Chapter_4.md
    - "Chapter 5: Antenna Board Preintegration": Assembly_Guide_V2/Chapter_5.md
    - "Chapter 6: Structure Preintegration": Assembly_Guide_V2/Chapter_6.md
    - "Chapter 7: Preintegration Testing Overview":
      - "Preintegration Testing Index": Assembly_Guide_V2/Chapter_7_testing/index.md
      - "Solar Board Testing": Assembly_Guide_V2/Chapter_7_testing/solar_board_testing.md
      - "Battery Board Testing": Assembly_Guide_V2/Chapter_7_testing/battery_board_testing.md
      - "Flight Controller Testing": Assembly_Guide_V2/Chapter_7_testing/flight_computer_testing.md
      - "FlatSat Testing": Assembly_Guide_V2/Chapter_7_testing/flatsat_testing.md
    - "Chapter 8: Integration Procedure": Assembly_Guide_V2/Chapter_8.md
    - "Chapter 9: Final Tests": Assembly_Guide_V2/Chapter_9.md
  - Core Documentation: 
    - core_documentation/index.md
    - Quick Reference: core_documentation/quick_reference.md
    - Hardware: 
      - core_documentation/hardware/index.md
      - Battery Board: core_documentation/hardware/battery_board.md
      - 1U Structure: core_documentation/hardware/1U_structure.md # 1u-structure
      - Flight Control Board: core_documentation/hardware/FC_board.md # flight-control-board
      - XY Solar Panels: core_documentation/hardware/XY_solar_board.md
      - Z Solar Panels: core_documentation/hardware/Z_solar_board.md
      - FlatSat Dev Board: core_documentation/hardware/flatsat_dev_board.md
    - Software:
      - core_documentation/software/index.md
      - RMF9x Radio Usage: core_documentation/software/rfm_radio_usage.md
      - pysquared.py: core_documentation/software/pysquared.md
      - functions.py: core_documentation/software/functions.md
      - big_data.py: core_documentation/software/big_data.md
      - cdh.py: core_documentation/software/cdh.md
      - payload.py: core_documentation/software/payload.md
      - detumble.py: core_documentation/software/detumble.md
    - Legacy Documentation: 
      - Original Pleiades Concept Proposal: core_documentation/legacy/original_pleiades_proposal.md
      - Yearling-1 Block Diagram: core_documentation/legacy/yearling_1_block_diagram.md
      - Blue Dawn Hackathon: core_documentation/legacy/blue_dawn.md
      - Yearling Software Sword: core_documentation/legacy/yearling_software_sword.md
    - Testing:
      - core_documentation/testing/index.md
      - Testing Overview: core_documentation/testing/testing_overview.md
      - Testing Procedures: core_documentation/testing/testing_procedures.md
      - Testing Results: core_documentation/testing/testing_results.md
    - Mission Operations:
      - core_documentation/mission_operations/index.md
    - Programatic:
      - core_documentation/programatic/index.md
  - Publications: publications.md

extra:
  social:
    - icon: material/github 
      link: https://github.com/proveskit