site_name: The PROVES Kit Documentation

theme: 
  name: material
  features:
    - navigation.tabs
    - header.autohide
    - navigation.path

plugins:
  - search  # To have search functionality on the document

markdown_extensions:
  - attr_list
  - md_in_html

nav: # Setting up the navigation. The below list will be tabs on left panel
  - Home: index.md
  - Overview: overview.md # Overview of the project
  - Design: design_philosophy.md  # 
  - Assembly Guide: assembly_guide.md # Assembly guide
  - Core Documentation: 
    - Hardware: 
      - hardware/index.md
      - 1U Structure: 1U_structure.md # 1u-structure
      - Flight Control Board: FC_board.md # flight-control-board
      - XY Solar Panels: XY_solar_board.md
      - Z Solar Panels: Z_solar_board.md
      - Battery Board: battery_board.md
    - Software: software.md
