site_name: The PROVES Kit Documentation

theme: 
  name: material
  features:
    - navigation.tabs
    - header.autohide
    - navigation.path

plugins:
  - search  # To have search functionality on the document
  - mkdocs-pdf #PDF Embed Ability

markdown_extensions:
  - attr_list
  - md_in_html
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.pathconverter:
      base_path: 'DOCUMENTATION' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'

nav: # Setting up the navigation. The below list will be tabs on left panel
  - Home: 
    - Welcome: index.md
    - Overview: overview.md
    - Quick Start Guide: quick_start/index.md
    - Assembly Guide: assembly_guide/index.md
    - Core Documentation: core_documentation/index.md
    - Publications: publications.md
  - Overview:  # Overview of the project
    - Overview: overview.md
    - Design Philosophy: design_philosophy.md
  - Quick Start Guide: design_philosophy.md  # 
  - Assembly Guide:
    - Introduction: assembly_guide/introduction.md
    - "Chapter 0: Parts and Tools": assembly_guide/ch_0_parts_tools.md
    - "Chapter 1: Battery Board Preintegration": assembly_guide/ch_1_eps.md
    - "Chapter 2: Feet and Heater Assembly Preintegration": assembly_guide/ch_2_feet.md
    - "Chapter 3: Solar Boards Preintegration": assembly_guide/ch_3_solar.md
    - "Chapter 4: Flight Controller Board Preintegration": assembly_guide/ch_4_fc.md
    - "Chapter 5: Antenna Preintegration": assembly_guide/ch_5_antenna.md
    - "Chapter 6: Structure Preintegration": assembly_guide/ch_6_structure.md
    - "Chapter 7: Preintegration Testing Overview":
      - "Preintegration Testing Index": assembly_guide/ch_7_testing/index.md
      - "Solar Board Testing": assembly_guide/ch_7_testing/solar_board_testing.md
      - "Battery Board Testing": assembly_guide/ch_7_testing/battery_board_testing.md
      - "Flight Controller Testing": assembly_guide/ch_7_testing/flight_computer_testing.md
      - "FlatSat Testing": assembly_guide/ch_7_testing/flatsat_testing.md
    - "Chapter 8: Integration Procedure": assembly_guide/ch_8_integration.md
    - "Chapter 9: Final Tests": assembly_guide/ch_9_final_tests.md
    - assembly_guide/index.md
  - Core Documentation: 
    - core_documentation/index.md
    - Hardware: 
      - core_documentation/hardware/index.md
      - 1U Structure: core_documentation/hardware/1U_structure.md # 1u-structure
      - Flight Control Board: core_documentation/hardware/FC_board.md # flight-control-board
      - XY Solar Panels: core_documentation/hardware/XY_solar_board.md
      - Z Solar Panels: core_documentation/hardware/Z_solar_board.md
      - Battery Board: core_documentation/hardware/battery_board.md
    - Software:
      - core_documentation/software/index.md
      - pysquared.py: core_documentation/software/pysquared.md
      - functions.py: core_documentation/software/functions.md
      - big_data.py: core_documentation/software/big_data.md
      - cdh.py: core_documentation/software/cdh.md
      - payload.py: core_documentation/software/payload.md
      - detumble.py: core_documentation/software/detumble.md
  - Publications: publications.md

